apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
spec:
  ports:
  - name: "2379"
    port: 2379
    protocol: TCP
    targetPort: 2379
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
