- hosts: kube-master

  pre_tasks:

    - name: Rsync CCP configs
      synchronize:
        src: ../ccp/
        dest: /root/ccp/

  tasks:

    - name: Get namespaces
      shell: kubectl get namespace
      register: get_ns
      run_once: true

    - name: Deploy CCP
      shell: ccp --config-file=/root/ccp/ccp.conf deploy
      args:
        chdir: /root/ccp
      run_once: true
      when: get_ns.stdout.find('ccp') == -1
