- hosts: kube-master
  tasks:

    - set_fact:
        etcd_access_addresses: |-
          {% for item in groups['etcd'] -%}
            https://{{ item }}:2379{% if not loop.last %},{% endif %}
          {%- endfor %}

    - name: sync files
      template: src=./etcd-calico-svc.j2 dest=/var/tmp/etcd-calico-svc.yaml
      run_once: true

    - name: Get svc
      shell: kubectl get svc --namespace=default
      register: get_svc
      run_once: true

    - name: setup-etcd-to-pods-proxy
      shell: kubectl --namespace=default create -f /var/tmp/etcd-calico-svc.yaml
      run_once: true
      when: get_svc.stdout.find('etcd-calico') == -1

    - name: enable felix reporting
      shell: etcdctl --peers={{etcd_access_addresses}} set /calico/v1/config/ReportingIntervalSecs 60
      run_once: true
      when: ccp_calico_etcd_host|default('etcd') == "etcd-calico"
