- hosts: all
  tasks:

    - name: Test tunl0 routes
      shell: "! ip ro | grep '/26 via' | grep -v tunl0"
      when: ipip|default(false)

- hosts: kube-master
  tasks:

    - name: Get services
      shell: kubectl get svc --namespace=default
      register: get_svc
      run_once: true

    - name: Deploy netchecker
      shell: "curl -s https://raw.githubusercontent.com/aateem/netchecker-server/master/utils/deploy_netchecker.sh | bash"
      run_once: true
      when: get_svc.stdout.find('netchecker-service') == -1

    - name: Wait for netchecker server
      shell: "kubectl get pods | grep ^netchecker-server"
      run_once: true
      register: ncs_pod
      until: ncs_pod.stdout.find('Running') != -1
      retries: 120
      delay: 10

    - name: Wait for netchecker agents
      shell: "kubectl get pods | grep '^netchecker-agent-.*Running'"
      run_once: true
      register: nca_pod
      until: "{{ nca_pod.stdout_lines|length }} >= {{ groups['all']|length * 2 }}"
      retries: 120
      delay: 10

    - name: Sleep for 10 seconds
      pause: seconds=10

    - name: Get netchecker agents
      uri: url=http://localhost:31081/api/v1/agents/ return_content=yes
      run_once: true
      register: agents

    - name: Give some time to netchecker agents to report
      pause: seconds=90
      when: "{{ (agents.content|from_json|length) }} < {{ groups['all']|length * 2 }}"

    - name: Check netchecker status
      uri: url=http://localhost:31081/api/v1/connectivity_check status_code=204
      run_once: true
